### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matiksjea** [GabrielFJunkes/MultipleBedSpawn#31]
[18:25:20] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to MultipleBedSpawn v1.10
java.lang.NoSuchMethodError: 'org.bukkit.event.player.PlayerRespawnEvent$RespawnReason org.bukkit.event.player.PlayerRespawnEvent.getRespawnReason()'
	at me.gabrielfj.multiplebedspawn.listeners.PlayerRespawnListener.onPlayerRespawn(PlayerRespawnListener.java:38) ~[MultipleBedSpawn-1.10.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaf-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[leaf-api-1.19.3-R0.1-SNAPSHOT.jar:git-Leaf-"4ac45c3"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[leaf-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:683) ~[leaf-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:948) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:850) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:845) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleClientCommand(ServerGamePacketListenerImpl.java:2954) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.handle(ServerboundClientCommandPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.a(ServerboundClientCommandPacket.java:10) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at org.galemc.gale.executor.MinecraftServerBlockableEventLoop.lambda$tell$1(MinecraftServerBlockableEventLoop.java:83) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at org.galemc.gale.executor.thread.BaseThread.runTasksUntil(BaseThread.java:356) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at org.galemc.gale.executor.MinecraftServerBlockableEventLoop.managedBlock(MinecraftServerBlockableEventLoop.java:172) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1449) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:416) ~[leaf-1.19.3.jar:git-Leaf-"4ac45c3"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by GabiJunkes** [comment]
What is the context of this? How can I reproduce the error?

**Comment by GabiJunkes** [comment]
No response closing this issue. You can reopen it with more details.
It looks like you are using a fork of paper that is not supported, so I will not give priority but feel free to ask for help.
